import XNav from '@/components/XNav'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'INDITEX Next App',
  description: 'Generated by create next app v13',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <XNav />
        {children}
      </body>
    </html>
  )
}
