'use client'
import StyledComponentsRegistry from '@/app/registry'
import './globals.css'
import { Inter } from 'next/font/google'
import ReduxProvider from '@/lib/providers/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'INDITEX Next App',
//   description: 'Generated by create next app v13',
// }

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </ReduxProvider>
  )
}
