'use client'
import StyledComponentsRegistry from '@/lib/StyleRegistry'
import { store } from '@/lib/redux/store'
import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'INDITEX Next App',
  description: 'Generated by create next app v13',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </Provider>
  )
}
